/********************************************************************
* .\src\r_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error .\src\r_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevr_Dict();
extern G__DLLEXPORT void G__set_cpp_environmentr_Dict();
extern G__DLLEXPORT void G__cpp_setup_tagtabler_Dict();
extern G__DLLEXPORT void G__cpp_setup_inheritancer_Dict();
extern G__DLLEXPORT void G__cpp_setup_typetabler_Dict();
extern G__DLLEXPORT void G__cpp_setup_memvarr_Dict();
extern G__DLLEXPORT void G__cpp_setup_globalr_Dict();
extern G__DLLEXPORT void G__cpp_setup_memfuncr_Dict();
extern G__DLLEXPORT void G__cpp_setup_funcr_Dict();
extern G__DLLEXPORT void G__cpp_setupr_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./h/main.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__r_DictLN_TClass;
extern G__linked_taginfo G__r_DictLN_TBuffer;
extern G__linked_taginfo G__r_DictLN_TMemberInspector;
extern G__linked_taginfo G__r_DictLN_TObject;
extern G__linked_taginfo G__r_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__r_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__r_DictLN__RanitlEROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__r_DictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__r_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__r_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__r_DictLN_TList;
extern G__linked_taginfo G__r_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__r_DictLN_TCanvas;
extern G__linked_taginfo G__r_DictLN_TQObject;
extern G__linked_taginfo G__r_DictLN_TQObjSender;
extern G__linked_taginfo G__r_DictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__r_DictLN__RanitlETStringcOlongcOTStringmUcOTStringaNgR;
extern G__linked_taginfo G__r_DictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR;
extern G__linked_taginfo G__r_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__r_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__r_DictLN_TGObject;
extern G__linked_taginfo G__r_DictLN_TGWindow;
extern G__linked_taginfo G__r_DictLN_TGFrame;
extern G__linked_taginfo G__r_DictLN_TGCompositeFrame;
extern G__linked_taginfo G__r_DictLN_TGLayoutHints;
extern G__linked_taginfo G__r_DictLN_TGTextButton;
extern G__linked_taginfo G__r_DictLN_TGMainFrame;
extern G__linked_taginfo G__r_DictLN_TGTransientFrame;
extern G__linked_taginfo G__r_DictLN_TGGroupFrame;
extern G__linked_taginfo G__r_DictLN_TGPopupMenu;
extern G__linked_taginfo G__r_DictLN_TGMenuBar;
extern G__linked_taginfo G__r_DictLN_TGButton;
extern G__linked_taginfo G__r_DictLN_TGPictureButton;
extern G__linked_taginfo G__r_DictLN_TGCheckButton;
extern G__linked_taginfo G__r_DictLN_TGDockableFrame;
extern G__linked_taginfo G__r_DictLN_TGTextEntry;
extern G__linked_taginfo G__r_DictLN_TGNumberEntryField;
extern G__linked_taginfo G__r_DictLN_TGNumberEntry;
extern G__linked_taginfo G__r_DictLN_TGStatusBar;
extern G__linked_taginfo G__r_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__r_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__r_DictLN_TGraph;
extern G__linked_taginfo G__r_DictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__r_DictLN_TGListBox;
extern G__linked_taginfo G__r_DictLN_TGComboBox;
extern G__linked_taginfo G__r_DictLN_TGLabel;
extern G__linked_taginfo G__r_DictLN_Core;
extern G__linked_taginfo G__r_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__r_DictLN_TGTab;
extern G__linked_taginfo G__r_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__r_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__r_DictLN_Settings;
extern G__linked_taginfo G__r_DictLN_fChannelsFrame;
extern G__linked_taginfo G__r_DictLN_MainFrame;

/* STUB derived class for protected member access */
