//
// File generated by rootcint at Tue Jul 19 18:10:14 2011

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "r_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void Settings_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void Settings_Dictionary();
   static void *new_Settings(void *p = 0);
   static void *newArray_Settings(Long_t size, void *p);
   static void delete_Settings(void *p);
   static void deleteArray_Settings(void *p);
   static void destruct_Settings(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::Settings*)
   {
      ::Settings *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::Settings),0);
      static ::ROOT::TGenericClassInfo 
         instance("Settings", "c_Settings.h", 6,
                  typeid(::Settings), DefineBehavior(ptr, ptr),
                  0, &Settings_Dictionary, isa_proxy, 0,
                  sizeof(::Settings) );
      instance.SetNew(&new_Settings);
      instance.SetNewArray(&newArray_Settings);
      instance.SetDelete(&delete_Settings);
      instance.SetDeleteArray(&deleteArray_Settings);
      instance.SetDestructor(&destruct_Settings);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::Settings*)
   {
      return GenerateInitInstanceLocal((::Settings*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Settings*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void Settings_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::Settings*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   void fChannelsFrame_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void fChannelsFrame_Dictionary();
   static void delete_fChannelsFrame(void *p);
   static void deleteArray_fChannelsFrame(void *p);
   static void destruct_fChannelsFrame(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::fChannelsFrame*)
   {
      ::fChannelsFrame *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::fChannelsFrame),0);
      static ::ROOT::TGenericClassInfo 
         instance("fChannelsFrame", "f_Channels.h", 51,
                  typeid(::fChannelsFrame), DefineBehavior(ptr, ptr),
                  0, &fChannelsFrame_Dictionary, isa_proxy, 0,
                  sizeof(::fChannelsFrame) );
      instance.SetDelete(&delete_fChannelsFrame);
      instance.SetDeleteArray(&deleteArray_fChannelsFrame);
      instance.SetDestructor(&destruct_fChannelsFrame);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::fChannelsFrame*)
   {
      return GenerateInitInstanceLocal((::fChannelsFrame*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::fChannelsFrame*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void fChannelsFrame_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::fChannelsFrame*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   void MainFrame_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void delete_MainFrame(void *p);
   static void deleteArray_MainFrame(void *p);
   static void destruct_MainFrame(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::MainFrame*)
   {
      ::MainFrame *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::MainFrame >(0);
      static ::ROOT::TGenericClassInfo 
         instance("MainFrame", ::MainFrame::Class_Version(), "f_MainFrame.h", 47,
                  typeid(::MainFrame), DefineBehavior(ptr, ptr),
                  &::MainFrame::Dictionary, isa_proxy, 0,
                  sizeof(::MainFrame) );
      instance.SetDelete(&delete_MainFrame);
      instance.SetDeleteArray(&deleteArray_MainFrame);
      instance.SetDestructor(&destruct_MainFrame);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::MainFrame*)
   {
      return GenerateInitInstanceLocal((::MainFrame*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::MainFrame*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *MainFrame::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *MainFrame::Class_Name()
{
   return "MainFrame";
}

//______________________________________________________________________________
const char *MainFrame::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::MainFrame*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int MainFrame::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::MainFrame*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void MainFrame::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::MainFrame*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *MainFrame::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::MainFrame*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void MainFrame::Streamer(TBuffer &R__b)
{
   // Stream an object of class MainFrame.

   TGMainFrame::Streamer(R__b);
}

//______________________________________________________________________________
void MainFrame::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class MainFrame.
      typedef ::MainFrame msvc_bug_workaround;
      TClass *R__cl = msvc_bug_workaround::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*fMenuDock", &fMenuDock);
      R__insp.Inspect(R__cl, R__parent, "*fMenuBar", &fMenuBar);
      R__insp.Inspect(R__cl, R__parent, "*fMenuFile", &fMenuFile);
      R__insp.Inspect(R__cl, R__parent, "*fMenuSettings", &fMenuSettings);
      R__insp.Inspect(R__cl, R__parent, "*fMenuHelp", &fMenuHelp);
      R__insp.Inspect(R__cl, R__parent, "*fMenuBarLayout", &fMenuBarLayout);
      R__insp.Inspect(R__cl, R__parent, "*fMenuBarItemLayout", &fMenuBarItemLayout);
      R__insp.Inspect(R__cl, R__parent, "*fMenuBarHelpLayout", &fMenuBarHelpLayout);
      R__insp.Inspect(R__cl, R__parent, "*fMiddleFrame", &fMiddleFrame);
      R__insp.Inspect(R__cl, R__parent, "*fEcanvas1", &fEcanvas1);
      R__insp.Inspect(R__cl, R__parent, "fIDcanvas1", &fIDcanvas1);
      R__insp.Inspect(R__cl, R__parent, "*fcanvasMPD1", &fcanvasMPD1);
      R__insp.Inspect(R__cl, R__parent, "*graph1", &graph1);
      R__insp.Inspect(R__cl, R__parent, "*fLGroupFrame", &fLGroupFrame);
      R__insp.Inspect(R__cl, R__parent, "*fRGroupFrame", &fRGroupFrame);
      R__insp.Inspect(R__cl, R__parent, "*fgroupGraph", &fgroupGraph);
      R__insp.Inspect(R__cl, R__parent, "*fgroupMeas", &fgroupMeas);
      R__insp.Inspect(R__cl, R__parent, "*fNumEvents", &fNumEvents);
      R__insp.Inspect(R__cl, R__parent, "*fNumTime", &fNumTime);
      R__insp.Inspect(R__cl, R__parent, "*fNumBaseline", &fNumBaseline);
      R__insp.Inspect(R__cl, R__parent, "*fNumAmplitude", &fNumAmplitude);
      R__insp.Inspect(R__cl, R__parent, "*fNumCharge", &fNumCharge);
      R__insp.Inspect(R__cl, R__parent, "*fNumCountRate", &fNumCountRate);
      R__insp.Inspect(R__cl, R__parent, "*fNumCounter", &fNumCounter);
      R__insp.Inspect(R__cl, R__parent, "*fNumRxRate", &fNumRxRate);
      R__insp.Inspect(R__cl, R__parent, "*fgroupTrigg", &fgroupTrigg);
      R__insp.Inspect(R__cl, R__parent, "*fComboTri", &fComboTri);
      R__insp.Inspect(R__cl, R__parent, "*fNumTreshold", &fNumTreshold);
      R__insp.Inspect(R__cl, R__parent, "*fPButtonSlope", &fPButtonSlope);
      R__insp.Inspect(R__cl, R__parent, "*fButtonApply", &fButtonApply);
      R__insp.Inspect(R__cl, R__parent, "*fgroupCtrl", &fgroupCtrl);
      R__insp.Inspect(R__cl, R__parent, "*fButtonRunMPD1", &fButtonRunMPD1);
      R__insp.Inspect(R__cl, R__parent, "*fScal", &fScal);
      R__insp.Inspect(R__cl, R__parent, "*fSave", &fSave);
      R__insp.Inspect(R__cl, R__parent, "*fTable", &fTable);
      R__insp.Inspect(R__cl, R__parent, "*fStatusBar", &fStatusBar);
      R__insp.Inspect(R__cl, R__parent, "*core", &core);
      R__insp.Inspect(R__cl, R__parent, "*setts", &setts);
      R__insp.Inspect(R__cl, R__parent, "*fChannels", &fChannels);
      R__insp.Inspect(R__cl, R__parent, "fbslope", &fbslope);
      R__insp.Inspect(R__cl, R__parent, "saveCal", &saveCal);
      R__insp.Inspect(R__cl, R__parent, "saveWave", &saveWave);
      R__insp.Inspect(R__cl, R__parent, "saveTable", &saveTable);
      TGMainFrame::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_MainFrame(void *p) {
      delete ((::MainFrame*)p);
   }
   static void deleteArray_MainFrame(void *p) {
      delete [] ((::MainFrame*)p);
   }
   static void destruct_MainFrame(void *p) {
      typedef ::MainFrame current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::MainFrame

namespace ROOT {
   // Wrapper around operator delete
   static void delete_fChannelsFrame(void *p) {
      delete ((::fChannelsFrame*)p);
   }
   static void deleteArray_fChannelsFrame(void *p) {
      delete [] ((::fChannelsFrame*)p);
   }
   static void destruct_fChannelsFrame(void *p) {
      typedef ::fChannelsFrame current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::fChannelsFrame

namespace ROOT {
   // Wrappers around operator new
   static void *new_Settings(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::Settings : new ::Settings;
   }
   static void *newArray_Settings(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::Settings[nElements] : new ::Settings[nElements];
   }
   // Wrapper around operator delete
   static void delete_Settings(void *p) {
      delete ((::Settings*)p);
   }
   static void deleteArray_Settings(void *p) {
      delete [] ((::Settings*)p);
   }
   static void destruct_Settings(void *p) {
      typedef ::Settings current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::Settings

/********************************************************
* ..\src\r_Dict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtabler_Dict();

extern "C" void G__set_cpp_environmentr_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("main.h");
  G__cpp_reset_tagtabler_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevr_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Settings */
static int G__r_Dict_831_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Settings* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Settings[n];
     } else {
       p = new((void*) gvp) Settings[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Settings;
     } else {
       p = new((void*) gvp) Settings;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__r_DictLN_Settings));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_831_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Settings*) G__getstructoffset())->SetChanConfig((unsigned char) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_831_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 98, (long) ((Settings*) G__getstructoffset())->GetChanConfig());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_831_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Settings*) G__getstructoffset())->SetChanTotal((unsigned char) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_831_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 98, (long) ((Settings*) G__getstructoffset())->GetChanTotal());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__r_Dict_831_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   Settings* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new Settings(*(Settings*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__r_DictLN_Settings));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Settings G__TSettings;
static int G__r_Dict_831_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Settings*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Settings*) (soff+(sizeof(Settings)*i)))->~G__TSettings();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Settings*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Settings*) (soff))->~G__TSettings();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__r_Dict_831_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Settings* dest = (Settings*) G__getstructoffset();
   *dest = *(Settings*) libp->para[0].ref;
   const Settings& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* fChannelsFrame */
static int G__r_Dict_832_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const fChannelsFrame*) G__getstructoffset())->GetListOfSignals());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((fChannelsFrame*) G__getstructoffset())->Connect((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (void*) G__int(libp->para[2]), (const char*) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 103, (long) ((fChannelsFrame*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 103, (long) ((fChannelsFrame*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 103, (long) ((fChannelsFrame*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 103, (long) ((fChannelsFrame*) G__getstructoffset())->Disconnect());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((fChannelsFrame*) G__getstructoffset())->HighPriority((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((fChannelsFrame*) G__getstructoffset())->HighPriority((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((fChannelsFrame*) G__getstructoffset())->LowPriority((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((fChannelsFrame*) G__getstructoffset())->LowPriority((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   G__va_arg_buf G__va_arg_bufobj;
   G__va_arg_put(&G__va_arg_bufobj, libp, 2);
      ((fChannelsFrame*) G__getstructoffset())->EmitVA((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]), G__va_arg_bufobj);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long64_t) G__Longlong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong64_t) G__ULonglong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Char_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UChar_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Short_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UShort_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Float_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->Destroyed();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->ChangedBy((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->Message((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   fChannelsFrame* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 5:
     //m: 5
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new fChannelsFrame(
(const TGWindow*) G__int(libp->para[0]), (const TGWindow*) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (UInt_t) G__int(libp->para[4]));
     } else {
       p = new((void*) gvp) fChannelsFrame(
(const TGWindow*) G__int(libp->para[0]), (const TGWindow*) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (UInt_t) G__int(libp->para[4]));
     }
     break;
   case 4:
     //m: 4
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new fChannelsFrame(
(const TGWindow*) G__int(libp->para[0]), (const TGWindow*) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3]));
     } else {
       p = new((void*) gvp) fChannelsFrame(
(const TGWindow*) G__int(libp->para[0]), (const TGWindow*) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__r_DictLN_fChannelsFrame));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->DoClose();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->CloseWindow();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->DoOK();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->DoCancel();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->DoTab((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((fChannelsFrame*) G__getstructoffset())->HandleButtons((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((fChannelsFrame*) G__getstructoffset())->HandleButtons();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((fChannelsFrame*) G__getstructoffset())->HandleChanList((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((fChannelsFrame*) G__getstructoffset())->HandleChanList();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_832_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((fChannelsFrame*) G__getstructoffset())->SettingsChanged();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef fChannelsFrame G__TfChannelsFrame;
static int G__r_Dict_832_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (fChannelsFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((fChannelsFrame*) (soff+(sizeof(fChannelsFrame)*i)))->~G__TfChannelsFrame();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (fChannelsFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((fChannelsFrame*) (soff))->~G__TfChannelsFrame();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* MainFrame */
static int G__r_Dict_834_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MainFrame* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new MainFrame(
(const TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) MainFrame(
(const TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__r_DictLN_MainFrame));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_834_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MainFrame*) G__getstructoffset())->HandleMenu((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_834_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MainFrame*) G__getstructoffset())->SettingsUpdate();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_834_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MainFrame*) G__getstructoffset())->HandleComboTri();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_834_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MainFrame*) G__getstructoffset())->FButtonSlope();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_834_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MainFrame*) G__getstructoffset())->FButtonConfig();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_834_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MainFrame*) G__getstructoffset())->FButtonRunMPD1();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_834_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MainFrame*) G__getstructoffset())->HandleCheckBoxes();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_834_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((MainFrame*) G__getstructoffset())->Update());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_834_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MainFrame*) G__getstructoffset())->LocalChanged();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_834_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) MainFrame::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_834_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MainFrame::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_834_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) MainFrame::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_834_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      MainFrame::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_834_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MainFrame*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_834_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MainFrame::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_834_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) MainFrame::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_834_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MainFrame::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__r_Dict_834_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) MainFrame::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef MainFrame G__TMainFrame;
static int G__r_Dict_834_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (MainFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((MainFrame*) (soff+(sizeof(MainFrame)*i)))->~G__TMainFrame();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (MainFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((MainFrame*) (soff))->~G__TMainFrame();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Settings */

/* fChannelsFrame */

/* MainFrame */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncr_Dict {
 public:
  G__Sizep2memfuncr_Dict(): p(&G__Sizep2memfuncr_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncr_Dict::*p)();
};

size_t G__get_sizep2memfuncr_Dict()
{
  G__Sizep2memfuncr_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancer_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__r_DictLN_MainFrame))) {
     MainFrame *G__Lderived;
     G__Lderived=(MainFrame*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__r_DictLN_MainFrame),G__get_linked_tagnum(&G__r_DictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__r_DictLN_MainFrame),G__get_linked_tagnum(&G__r_DictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__r_DictLN_MainFrame),G__get_linked_tagnum(&G__r_DictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__r_DictLN_MainFrame),G__get_linked_tagnum(&G__r_DictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__r_DictLN_MainFrame),G__get_linked_tagnum(&G__r_DictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__r_DictLN_MainFrame),G__get_linked_tagnum(&G__r_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__r_DictLN_MainFrame),G__get_linked_tagnum(&G__r_DictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetabler_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("UChar_t",98,-1,0,-1);
   G__setnewtype(-1,"Unsigned Character 1 byte (unsigned char)",0);
   G__search_typename2("Short_t",115,-1,0,-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes (short)",0);
   G__search_typename2("UShort_t",114,-1,0,-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes (unsigned short)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Long_t",108,-1,0,-1);
   G__setnewtype(-1,"Signed long integer 4 bytes (long)",0);
   G__search_typename2("ULong_t",107,-1,0,-1);
   G__setnewtype(-1,"Unsigned long integer 4 bytes (unsigned long)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("Long64_t",110,-1,0,-1);
   G__setnewtype(-1,"Portable signed long integer 8 bytes",0);
   G__search_typename2("ULong64_t",109,-1,0,-1);
   G__setnewtype(-1,"Portable unsigned long integer 8 bytes",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__r_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("_Ranit<ROOT::TSchemaHelper,difference_type,const_pointer,const_reference>",117,G__get_linked_tagnum(&G__r_DictLN__RanitlEROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,G__get_linked_tagnum(&G__r_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__r_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__r_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__r_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::reference>",117,G__get_linked_tagnum(&G__r_DictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__r_DictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long>",117,G__get_linked_tagnum(&G__r_DictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*>",117,G__get_linked_tagnum(&G__r_DictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__r_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__r_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__r_DictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__r_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__r_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__r_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__r_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__r_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__r_DictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("_Ranit<TString,difference_type,const_pointer,const_reference>",117,G__get_linked_tagnum(&G__r_DictLN__RanitlETStringcOlongcOTStringmUcOTStringaNgR),0,G__get_linked_tagnum(&G__r_DictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__r_DictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__r_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__r_DictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TString,allocator<TString> >::iterator>::iterator_category,iterator_traits<vector<TString,allocator<TString> >::iterator>::value_type,iterator_traits<vector<TString,allocator<TString> >::iterator>::difference_type,iterator_traits<vector<TString,allocator<TString> >::iterator>::pointer,iterator_traits<vector<TString,allocator<TString> >::iterator>::reference>",117,G__get_linked_tagnum(&G__r_DictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TString>",117,G__get_linked_tagnum(&G__r_DictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TString,long>",117,G__get_linked_tagnum(&G__r_DictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TString,long,TString*>",117,G__get_linked_tagnum(&G__r_DictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__r_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__r_DictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TString,allocator<TString> >::const_iterator>::iterator_category,iterator_traits<vector<TString,allocator<TString> >::const_iterator>::value_type,iterator_traits<vector<TString,allocator<TString> >::const_iterator>::difference_type,iterator_traits<vector<TString,allocator<TString> >::const_iterator>::pointer,iterator_traits<vector<TString,allocator<TString> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__r_DictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__r_DictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__r_DictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__r_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__r_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__r_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__r_DictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__r_DictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* Settings */
static void G__setup_memvarSettings(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__r_DictLN_Settings));
   { Settings *p; p=(Settings*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* fChannelsFrame */
static void G__setup_memvarfChannelsFrame(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__r_DictLN_fChannelsFrame));
   { fChannelsFrame *p; p=(fChannelsFrame*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__r_DictLN_TQObjSender),-1,-1,4,"fQObject=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_Settings),-1,-1,4,"setts=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGLabel),-1,-1,4,"ChanLabel=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGTransientFrame),-1,-1,4,"fMain=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGCompositeFrame),-1,-1,4,"fFrame1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGCompositeFrame),-1,-1,4,"fF1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGCompositeFrame),-1,-1,4,"fF2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGCompositeFrame),-1,-1,4,"fF3=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGCompositeFrame),-1,-1,4,"fF4=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGCompositeFrame),-1,-1,4,"fF5=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGGroupFrame),-1,-1,4,"fF6=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGGroupFrame),-1,-1,4,"fF7=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGButton),-1,-1,4,"fOkButton=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGButton),-1,-1,4,"fCancelButton=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGButton),-1,-1,4,"fStartB=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGButton),-1,-1,4,"fStopB=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGButton),-1,-1,4,"fBtn1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGButton),-1,-1,4,"fBtn2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGButton),-1,-1,4,"fChk1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGButton),-1,-1,4,"fChk2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGButton),-1,-1,4,"fRad1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGButton),-1,-1,4,"fRad2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGPictureButton),-1,-1,4,"fPicBut1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGCheckButton),-1,-1,4,"fCheck1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGCheckButton),-1,-1,4,"fCheckMulti=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGListBox),-1,-1,4,"fChanList=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGComboBox),-1,-1,4,"fCombo=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGTab),-1,-1,4,"fTab=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGTextEntry),-1,-1,4,"fTxt1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGTextEntry),-1,-1,4,"fTxt2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGLayoutHints),-1,-1,4,"fL1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGLayoutHints),-1,-1,4,"fL2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGLayoutHints),-1,-1,4,"fL3=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGLayoutHints),-1,-1,4,"fL4=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TRootEmbeddedCanvas),-1,-1,4,"fEc1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TRootEmbeddedCanvas),-1,-1,4,"fEc2=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fFirstEntry=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fLastEntry=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* MainFrame */
static void G__setup_memvarMainFrame(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__r_DictLN_MainFrame));
   { MainFrame *p; p=(MainFrame*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGDockableFrame),-1,-1,4,"fMenuDock=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGMenuBar),-1,-1,4,"fMenuBar=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGPopupMenu),-1,-1,4,"fMenuFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGPopupMenu),-1,-1,4,"fMenuSettings=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGPopupMenu),-1,-1,4,"fMenuHelp=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGLayoutHints),-1,-1,4,"fMenuBarLayout=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGLayoutHints),-1,-1,4,"fMenuBarItemLayout=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGLayoutHints),-1,-1,4,"fMenuBarHelpLayout=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGCompositeFrame),-1,-1,4,"fMiddleFrame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TRootEmbeddedCanvas),-1,-1,4,"fEcanvas1=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fIDcanvas1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TCanvas),-1,-1,4,"fcanvasMPD1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGraph),-1,-1,4,"graph1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGCompositeFrame),-1,-1,4,"fLGroupFrame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGCompositeFrame),-1,-1,4,"fRGroupFrame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGGroupFrame),-1,-1,4,"fgroupGraph=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGGroupFrame),-1,-1,4,"fgroupMeas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGNumberEntryField),-1,-1,4,"fNumEvents=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGNumberEntryField),-1,-1,4,"fNumTime=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGNumberEntryField),-1,-1,4,"fNumBaseline=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGNumberEntryField),-1,-1,4,"fNumAmplitude=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGNumberEntryField),-1,-1,4,"fNumCharge=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGNumberEntryField),-1,-1,4,"fNumCountRate=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGNumberEntryField),-1,-1,4,"fNumCounter=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGNumberEntryField),-1,-1,4,"fNumRxRate=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGGroupFrame),-1,-1,4,"fgroupTrigg=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGComboBox),-1,-1,4,"fComboTri=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGNumberEntry),-1,-1,4,"fNumTreshold=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGPictureButton),-1,-1,4,"fPButtonSlope=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGTextButton),-1,-1,4,"fButtonApply=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGGroupFrame),-1,-1,4,"fgroupCtrl=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGTextButton),-1,-1,4,"fButtonRunMPD1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGCheckButton),-1,-1,4,"fScal=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGCheckButton),-1,-1,4,"fSave=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGCheckButton),-1,-1,4,"fTable=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TGStatusBar),-1,-1,4,"fStatusBar=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_Core),-1,-1,4,"core=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_Settings),-1,-1,4,"setts=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_fChannelsFrame),-1,-1,4,"fChannels=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"fbslope=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"saveCal=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"saveWave=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"saveTable=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__r_DictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarr_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncSettings(void) {
   /* Settings */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__r_DictLN_Settings));
   G__memfunc_setup("Settings",849,G__r_Dict_831_0_1, 105, G__get_linked_tagnum(&G__r_DictLN_Settings), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetChanConfig",1276,G__r_Dict_831_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "b - - 0 - nc_config", "{ c_config = nc_config; }*/", (void*) NULL, 0);
   G__memfunc_setup("GetChanConfig",1264,G__r_Dict_831_0_3, 98, -1, -1, 0, 0, 1, 1, 0, "", "{ return c_config; }*/", (void*) NULL, 0);
   G__memfunc_setup("SetChanTotal",1194,G__r_Dict_831_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "b - - 0 - nc_total", "{ c_total = nc_total; }*/", (void*) NULL, 0);
   G__memfunc_setup("GetChanTotal",1182,G__r_Dict_831_0_5, 98, -1, -1, 0, 0, 1, 1, 0, "", "{ return c_total; }*/", (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("Settings", 849, G__r_Dict_831_0_6, (int) ('i'), G__get_linked_tagnum(&G__r_DictLN_Settings), -1, 0, 1, 1, 1, 0, "u 'Settings' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~Settings", 975, G__r_Dict_831_0_7, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__r_Dict_831_0_8, (int) ('u'), G__get_linked_tagnum(&G__r_DictLN_Settings), -1, 1, 1, 1, 1, 0, "u 'Settings' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncfChannelsFrame(void) {
   /* fChannelsFrame */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__r_DictLN_fChannelsFrame));
   G__memfunc_setup("GetListOfSignals",1602,G__r_Dict_832_0_1, 85, G__get_linked_tagnum(&G__r_DictLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Connect",714,G__r_Dict_832_0_2, 103, -1, G__defined_typename("Bool_t"), 0, 4, 1, 1, 0, 
"C - - 10 - sig C - - 10 - cl "
"Y - - 0 - rcvr C - - 10 - slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Disconnect",1034,G__r_Dict_832_0_3, 103, -1, G__defined_typename("Bool_t"), 0, 3, 1, 1, 0, 
"C - - 10 '0' sig Y - - 0 '0' rcvr "
"C - - 10 '0' slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HighPriority",1250,G__r_Dict_832_0_4, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LowPriority",1172,G__r_Dict_832_0_5, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EmitVA",550,G__r_Dict_832_0_6, 121, -1, -1, 0, 2, 8, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - nargs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__r_Dict_832_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - signal", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__r_Dict_832_0_8, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal C - - 10 - params", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__r_Dict_832_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal L - 'Long_t' 0 - paramArr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__r_Dict_832_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal d - 'Double_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__r_Dict_832_0_11, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal l - 'Long_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__r_Dict_832_0_12, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal n - 'Long64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__r_Dict_832_0_13, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal m - 'ULong64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__r_Dict_832_0_14, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal g - 'Bool_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__r_Dict_832_0_15, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal c - 'Char_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__r_Dict_832_0_16, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal b - 'UChar_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__r_Dict_832_0_17, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal s - 'Short_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__r_Dict_832_0_18, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal r - 'UShort_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__r_Dict_832_0_19, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__r_Dict_832_0_20, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal h - 'UInt_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__r_Dict_832_0_21, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal k - 'ULong_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__r_Dict_832_0_22, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal f - 'Float_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Destroyed",947,G__r_Dict_832_0_23, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChangedBy",869,G__r_Dict_832_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - method", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Message",709,G__r_Dict_832_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - msg", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("fChannelsFrame",1405,G__r_Dict_832_0_26, 105, G__get_linked_tagnum(&G__r_DictLN_fChannelsFrame), -1, 0, 5, 1, 1, 0, 
"U 'TGWindow' - 10 - p U 'TGWindow' - 10 - main "
"h - 'UInt_t' 0 - w h - 'UInt_t' 0 - h "
"h - 'UInt_t' 0 'kVerticalFrame' options", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoClose",681,G__r_Dict_832_0_27, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CloseWindow",1134,G__r_Dict_832_0_28, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoOK",333,G__r_Dict_832_0_29, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoCancel",761,G__r_Dict_832_0_30, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoTab",458,G__r_Dict_832_0_31, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HandleButtons",1339,G__r_Dict_832_0_32, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 '-1' id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HandleChanList",1378,G__r_Dict_832_0_33, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 '-1' id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SettingsChanged",1531,G__r_Dict_832_0_34, 121, -1, -1, 0, 0, 1, 1, 0, "", "*SIGNAL*", (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~fChannelsFrame", 1531, G__r_Dict_832_0_35, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncMainFrame(void) {
   /* MainFrame */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__r_DictLN_MainFrame));
   G__memfunc_setup("MainFrame",880,G__r_Dict_834_0_1, 105, G__get_linked_tagnum(&G__r_DictLN_MainFrame), -1, 0, 3, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CloseWindow",1134,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("HandleMenu",993,G__r_Dict_834_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SettingsUpdate",1460,G__r_Dict_834_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HandleComboTri",1387,G__r_Dict_834_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FButtonSlope",1221,G__r_Dict_834_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FButtonConfig",1304,G__r_Dict_834_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FButtonRunMPD1",1289,G__r_Dict_834_0_8, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HandleCheckBoxes",1579,G__r_Dict_834_0_9, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Update",611,G__r_Dict_834_0_10, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("LocalChanged",1173,G__r_Dict_834_0_11, 121, -1, -1, 0, 0, 1, 1, 0, "", "*SIGNAL*", (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__r_Dict_834_0_12, 85, G__get_linked_tagnum(&G__r_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&MainFrame::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__r_Dict_834_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MainFrame::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__r_Dict_834_0_14, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&MainFrame::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__r_Dict_834_0_15, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&MainFrame::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__r_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__r_Dict_834_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__r_Dict_834_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MainFrame::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__r_Dict_834_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&MainFrame::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__r_Dict_834_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MainFrame::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__r_Dict_834_0_23, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&MainFrame::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~MainFrame", 1006, G__r_Dict_834_0_24, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncr_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
}

static void G__cpp_setup_global8() {
}

static void G__cpp_setup_global9() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalr_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
  G__cpp_setup_global8();
  G__cpp_setup_global9();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcr_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__r_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__r_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__r_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__r_DictLN__RanitlEROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR = { "_Ranit<ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*,ROOT::TSchemaHelper&>" , 115 , -1 };
G__linked_taginfo G__r_DictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR = { "iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*,ROOT::TSchemaHelper&>" , 115 , -1 };
G__linked_taginfo G__r_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__r_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__r_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__r_DictLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TQObjSender = { "TQObjSender" , 99 , -1 };
G__linked_taginfo G__r_DictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__r_DictLN__RanitlETStringcOlongcOTStringmUcOTStringaNgR = { "_Ranit<TString,long,TString*,TString&>" , 115 , -1 };
G__linked_taginfo G__r_DictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR = { "iterator<random_access_iterator_tag,TString,long,TString*,TString&>" , 115 , -1 };
G__linked_taginfo G__r_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__r_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGLayoutHints = { "TGLayoutHints" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGTextButton = { "TGTextButton" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGTransientFrame = { "TGTransientFrame" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGGroupFrame = { "TGGroupFrame" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGPopupMenu = { "TGPopupMenu" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGMenuBar = { "TGMenuBar" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGButton = { "TGButton" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGPictureButton = { "TGPictureButton" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGCheckButton = { "TGCheckButton" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGDockableFrame = { "TGDockableFrame" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGTextEntry = { "TGTextEntry" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGNumberEntryField = { "TGNumberEntryField" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGNumberEntry = { "TGNumberEntry" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGStatusBar = { "TGStatusBar" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGraph = { "TGraph" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGListBox = { "TGListBox" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGComboBox = { "TGComboBox" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGLabel = { "TGLabel" , 99 , -1 };
G__linked_taginfo G__r_DictLN_Core = { "Core" , 99 , -1 };
G__linked_taginfo G__r_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TGTab = { "TGTab" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__r_DictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__r_DictLN_Settings = { "Settings" , 99 , -1 };
G__linked_taginfo G__r_DictLN_fChannelsFrame = { "fChannelsFrame" , 99 , -1 };
G__linked_taginfo G__r_DictLN_MainFrame = { "MainFrame" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtabler_Dict() {
  G__r_DictLN_TClass.tagnum = -1 ;
  G__r_DictLN_TBuffer.tagnum = -1 ;
  G__r_DictLN_TMemberInspector.tagnum = -1 ;
  G__r_DictLN_TObject.tagnum = -1 ;
  G__r_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__r_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__r_DictLN__RanitlEROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR.tagnum = -1 ;
  G__r_DictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR.tagnum = -1 ;
  G__r_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__r_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__r_DictLN_TList.tagnum = -1 ;
  G__r_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__r_DictLN_TCanvas.tagnum = -1 ;
  G__r_DictLN_TQObject.tagnum = -1 ;
  G__r_DictLN_TQObjSender.tagnum = -1 ;
  G__r_DictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__r_DictLN__RanitlETStringcOlongcOTStringmUcOTStringaNgR.tagnum = -1 ;
  G__r_DictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR.tagnum = -1 ;
  G__r_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__r_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__r_DictLN_TGObject.tagnum = -1 ;
  G__r_DictLN_TGWindow.tagnum = -1 ;
  G__r_DictLN_TGFrame.tagnum = -1 ;
  G__r_DictLN_TGCompositeFrame.tagnum = -1 ;
  G__r_DictLN_TGLayoutHints.tagnum = -1 ;
  G__r_DictLN_TGTextButton.tagnum = -1 ;
  G__r_DictLN_TGMainFrame.tagnum = -1 ;
  G__r_DictLN_TGTransientFrame.tagnum = -1 ;
  G__r_DictLN_TGGroupFrame.tagnum = -1 ;
  G__r_DictLN_TGPopupMenu.tagnum = -1 ;
  G__r_DictLN_TGMenuBar.tagnum = -1 ;
  G__r_DictLN_TGButton.tagnum = -1 ;
  G__r_DictLN_TGPictureButton.tagnum = -1 ;
  G__r_DictLN_TGCheckButton.tagnum = -1 ;
  G__r_DictLN_TGDockableFrame.tagnum = -1 ;
  G__r_DictLN_TGTextEntry.tagnum = -1 ;
  G__r_DictLN_TGNumberEntryField.tagnum = -1 ;
  G__r_DictLN_TGNumberEntry.tagnum = -1 ;
  G__r_DictLN_TGStatusBar.tagnum = -1 ;
  G__r_DictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__r_DictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__r_DictLN_TGraph.tagnum = -1 ;
  G__r_DictLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__r_DictLN_TGListBox.tagnum = -1 ;
  G__r_DictLN_TGComboBox.tagnum = -1 ;
  G__r_DictLN_TGLabel.tagnum = -1 ;
  G__r_DictLN_Core.tagnum = -1 ;
  G__r_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__r_DictLN_TGTab.tagnum = -1 ;
  G__r_DictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__r_DictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__r_DictLN_Settings.tagnum = -1 ;
  G__r_DictLN_fChannelsFrame.tagnum = -1 ;
  G__r_DictLN_MainFrame.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtabler_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__r_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__r_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__r_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__r_DictLN__RanitlEROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR);
   G__get_linked_tagnum_fwd(&G__r_DictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR);
   G__get_linked_tagnum_fwd(&G__r_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__r_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TList);
   G__get_linked_tagnum_fwd(&G__r_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TCanvas);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TQObjSender);
   G__get_linked_tagnum_fwd(&G__r_DictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__r_DictLN__RanitlETStringcOlongcOTStringmUcOTStringaNgR);
   G__get_linked_tagnum_fwd(&G__r_DictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR);
   G__get_linked_tagnum_fwd(&G__r_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__r_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGLayoutHints);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGTextButton);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGTransientFrame);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGGroupFrame);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGPopupMenu);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGMenuBar);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGButton);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGPictureButton);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGCheckButton);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGDockableFrame);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGTextEntry);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGNumberEntryField);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGNumberEntry);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGStatusBar);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGraph);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TRootEmbeddedCanvas);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGListBox);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGComboBox);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGLabel);
   G__get_linked_tagnum_fwd(&G__r_DictLN_Core);
   G__get_linked_tagnum_fwd(&G__r_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TGTab);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__r_DictLN_TMatrixTBaselEdoublegR);
   G__tagtable_setup(G__get_linked_tagnum(&G__r_DictLN_Settings),sizeof(Settings),-1,1280,(char*)NULL,G__setup_memvarSettings,G__setup_memfuncSettings);
   G__tagtable_setup(G__get_linked_tagnum(&G__r_DictLN_fChannelsFrame),sizeof(fChannelsFrame),-1,33792,(char*)NULL,G__setup_memvarfChannelsFrame,G__setup_memfuncfChannelsFrame);
   G__tagtable_setup(G__get_linked_tagnum(&G__r_DictLN_MainFrame),sizeof(MainFrame),-1,62464,(char*)NULL,G__setup_memvarMainFrame,G__setup_memfuncMainFrame);
}
extern "C" void G__cpp_setupr_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupr_Dict()");
  G__set_cpp_environmentr_Dict();
  G__cpp_setup_tagtabler_Dict();

  G__cpp_setup_inheritancer_Dict();

  G__cpp_setup_typetabler_Dict();

  G__cpp_setup_memvarr_Dict();

  G__cpp_setup_memfuncr_Dict();
  G__cpp_setup_globalr_Dict();
  G__cpp_setup_funcr_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncr_Dict();
  return;
}
class G__cpp_setup_initr_Dict {
  public:
    G__cpp_setup_initr_Dict() { G__add_setup_func("r_Dict",(G__incsetup)(&G__cpp_setupr_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initr_Dict() { G__remove_setup_func("r_Dict"); }
};
G__cpp_setup_initr_Dict G__cpp_setup_initializerr_Dict;

